In [1]:
import numpy as np
arr=np.array([1,2,3,4,5,67,87])
arr

array([ 1,  2,  3,  4,  5, 67, 87])

In [2]:
a=[1,2,3,45,6,9]
a

[1, 2, 3, 45, 6, 9]

In [3]:
np.array(a)

array([ 1,  2,  3, 45,  6,  9])

In [16]:
l=[[1,2,3],[4,5,6],[7,8,9]]
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [19]:
arr=[[98,90,56,78],[23,45,67,89],[23,45,67,89]]
np.array(arr)

array([[98, 90, 56, 78],
       [23, 45, 67, 89],
       [23, 45, 67, 89]])

In [ ]:
#array generation function

In [20]:
arr=np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

In [21]:
arr=np.zeros((12,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [22]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [23]:
 arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
arr=np.zeros((12,8))
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [26]:
arr=np.zeros((3,6))
print(arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [27]:
arr=np.ones((2,5))
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [28]:
arr=np.ones((23,67))
arr
            

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]], shape=(23, 67))

In [38]:
arr=np.ones((8,2,3))
arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [40]:
arr=np.linspace(0,1,10)
arr

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [45]:
arr=np.linspace(1,5,10)
arr

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [54]:
#random generation function
arr=np.random.rand(78)
arr


array([3.09048914e-01, 5.38951447e-02, 1.75291241e-01, 4.46854018e-01,
       6.26164217e-01, 3.73265862e-01, 2.68644568e-01, 7.19504374e-01,
       5.59899884e-01, 5.84684433e-01, 8.42524739e-01, 9.88690544e-01,
       3.89106994e-01, 7.02178168e-01, 8.25403009e-01, 4.70344037e-04,
       7.20063434e-01, 5.53645683e-02, 1.48963476e-01, 1.97422109e-01,
       5.25320183e-01, 9.82079487e-01, 5.64829861e-01, 3.96391738e-01,
       6.17591500e-01, 2.74688392e-01, 9.66760948e-01, 7.03009596e-01,
       2.91827799e-01, 1.92714682e-01, 7.73527499e-01, 1.83040315e-01,
       8.01195208e-01, 1.61280793e-01, 7.47194885e-01, 7.76398710e-01,
       4.54388615e-01, 9.46891347e-01, 1.28489504e-02, 2.66489167e-01,
       7.58558841e-01, 9.71800689e-01, 7.60545246e-01, 4.38695428e-01,
       2.42957190e-02, 5.22577017e-02, 9.87103474e-01, 3.83702789e-01,
       5.11118170e-01, 5.90040327e-01, 9.89685754e-02, 2.14051367e-01,
       2.35571412e-01, 1.56111639e-01, 7.54534641e-01, 7.65318049e-01,
      

In [53]:
arr=np.random.randint(10,20,34)
arr

array([19, 16, 15, 12, 18, 10, 12, 13, 18, 17, 15, 11, 11, 16, 10, 12, 18,
       13, 13, 10, 16, 11, 13, 14, 12, 12, 11, 13, 10, 16, 11, 18, 17, 18],
      dtype=int32)

In [55]:
arr=np.random.randint(10,100,23)
arr

array([26, 92, 56, 88, 23, 32, 23, 84, 29, 71, 11, 53, 89, 75, 63, 27, 59,
       45, 55, 51, 77, 63, 43], dtype=int32)

In [61]:
arr=np.random.randn(10) # 99.7% values generate between -3 to 3 by randn function.
arr

array([-1.09527946,  0.33181685, -0.83411368,  1.28125403,  0.13146345,
        0.96172996,  1.8710812 , -1.16205931, -1.3180771 ,  1.01430476])

In [63]:
arr=np.random.randint(1200,1400,14)
arr


array([1304, 1275, 1346, 1396, 1362, 1303, 1350, 1317, 1293, 1327, 1296,
       1285, 1260, 1395], dtype=int32)

In [68]:
#array attributes.....
arr=[[1,2,3,4],[2,3,4,5],[4,5,6,7]]
arr


[[1, 2, 3, 4], [2, 3, 4, 5], [4, 5, 6, 7]]

In [65]:
np.array(arr)

array([[1, 2, 3, 4],
       [2, 3, 4, 5],
       [4, 5, 6, 7]])

In [83]:
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.shape)

(2, 3)


In [84]:
arr.shape

(2, 3)

In [88]:
arr=[[1,2,34,2],[23,45,23,45],[12,13,14,15]]
arr=np.array(arr)
print(arr.shape)

(3, 4)


In [89]:
arr.dtype

dtype('int64')

In [90]:
#array method
arr

array([[ 1,  2, 34,  2],
       [23, 45, 23, 45],
       [12, 13, 14, 15]])

In [91]:
arr.max()

np.int64(45)

In [93]:
arr.min()

np.int64(1)

In [94]:
arr.sum()

np.int64(229)

In [95]:
np.sum(arr,axis=1)#it add all the numbers of row axis=1 that means it add all the number of row

array([ 39, 136,  54])

In [96]:
np.sum(arr,axis=0)# at axis=0 it add all the numbers of column 

array([36, 60, 71, 62])

In [97]:
arr.mean()

np.float64(19.083333333333332)

In [129]:
# reshaping and resizing
arr=np.arange(1,31)
arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [130]:
arr=arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [140]:
arr=np.arange(1,43)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42])

In [141]:
arr=arr.reshape(6,7)
arr

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28],
       [29, 30, 31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40, 41, 42]])